/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * stlatica_internal_api
 * stlatica internal api
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'

export const getGetUserMock = () => ({followers_count: faker.number.int({min: undefined, max: undefined}), following_count: faker.number.int({min: undefined, max: undefined}), icon: faker.word.sample(), is_public: faker.datatype.boolean(), summary: faker.word.sample(), user_id: faker.word.sample(), username: faker.word.sample()})

export const getUserMock = () => [
http.get('*/internal/v1/users/:userId', async () => {
        await delay(1000);
        return new HttpResponse(JSON.stringify(getGetUserMock()),
          { 
            status: 200,
            headers: {
              'Content-Type': 'application/json',
            }
          }
        )
      }),]
