database ER: {
    actor: {
      shape: sql_table
      id: id {constraint: primary_key}
      userName: userName
      type: type
      inbox: inbox
      outbox: outbox
      following: following
      followers: followers
      liked: liked
    }
  }