# dummyと記載されている箇所についてはシェルスクリプト側で実際の値を指定する
pkgname="dummy"
output="dummy"
wipe=false
no-tests=true
no-hooks=true
no-rows-affected=true
no-driver-templates=true

templates=["dummy"]

[mysql]
dbname="stlatica"
host="localhost"
port=4000
user="root"
pass=""
sslmode="false"
whitelist=["sample_users","actors"]

[[types]]
[types.match]
name="created_at"
db_type="bigint"
nullable=false
[types.replace]
type="types.UnixTime"
[types.imports]
third_party=['"github.com/stlatica/stlatica/packages/backend/app/domains/types"']

[[types]]
[types.match]
name="updated_at"
db_type="bigint"
nullable=false
[types.replace]
type="types.UnixTime"
[types.imports]
third_party=['"github.com/stlatica/stlatica/packages/backend/app/domains/types"']

[[types]]
[types.match]
name="actor_id"
db_type="varchar"
nullable=false
[types.replace]
type="types.ActorID"
[types.imports]
third_party=['"github.com/stlatica/stlatica/packages/backend/app/domains/types"']
