// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

var TableNames = struct {
	Plats         string
	Timelines     string
	UserRelations string
	Users         string
}{
	Plats:         "plats",
	Timelines:     "timelines",
	UserRelations: "user_relations",
	Users:         "users",
}
