openapi: 3.0.3
info:
  title: stlatica_internal_api
  version: 0.1.0
  description: stlatica internal api
paths:
  /v1/sample_users/{sample_user_id}:
    get:
      operationId: getSampleUser
      tags:
        - SampleUser
      summary: Get sample_user
      description: get sample_user
      parameters:
        - in: path
          name: sample_user_id
          required: true
          description: sample_user_id
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleUser'
        500:
          description: internal server error
  /internal/v1/users/{user_id}:
    get:
      operationId: getUser
      tags:
        - User
      summary: get user
      description: get user
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: |
            bad request \
            error code:
            - 'BAD_REQUEST'
            - 'MISSING_PARAMETER'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: |
            not found \
            error code:
            - 'NOT_FOUND'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: |
            internal server error \
            error code:
            - 'INTERNAL_SERVER_ERROR'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        503:
          description: |
            service unavailable \
            error code:
            - 'SERVICE_UNAVAILABLE'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  parameters:
    user_id:
      in: path
      required: true
      name: user_id
      description: |
        userを識別するための一意のID \
        actor_idのfrontend向けエイリアスであり、actor_idと同一の値を持つ
      schema:
        type: string
      example: 'user_id'
  schemas:
    SampleUser:
      type: object
      required:
        - username
      properties:
        username:
          type: string
          example: 'sample_user'
    User:
      type: object
      description: user
      required:
        - user_id
        - username
        - summary
        - icon
        - followers_count
        - following_count
        - is_public
      properties:
        user_id:
          $ref: '#/components/schemas/UserID'
        username:
          type: string
          description: 画面上に表示されるユーザ名
          example: 'sample_actor'
        summary:
          type: string
          description: ユーザのプロフィール
          example: 'sample_actor'
        icon:
          type: string
          description: ユーザのアイコン画像のURL
          example: 'https://xxx/external/v1/images/sample_actor.png'
        followers_count:
          type: integer
          description: follower数
          example: 20
        following_count:
          type: integer
          description: following数
          example: 20
        is_public:
          type: boolean
          description: |
            公開アカウントであるかどうか \
            external apiのmanuallyApprovesFollowersと同一の値となる
          example: true
    UserID:
      description: |
        userを識別するための一意のID \
        actor_idのfrontend向けエイリアスであり、actor_idと同一の値を持つ
      type: string
      example: 'user_id'
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - 'BAD_REQUEST'
            - 'MISSING_PARAMETER'
            - 'NOT_FOUND'
            - 'INTERNAL_SERVER_ERROR'
            - 'SERVICE_UNAVAILABLE'
          example: 'INTERNAL_SERVER_ERROR'
        message:
          type: string
          example: 'error message'
