openapi: 3.0.3
info:
  title: stlatica_internal_api
  version: 0.1.0
  description: stlatica internal api
servers:
  - url: http://localhost:4010
    description: prism mock server
paths:
  /internal/v1/users/{user_id}:
    $ref: './paths/users.yaml#/users_{user_id}'
  /internal/v1/plats/{plat_id}:
    $ref: './paths/plat.yaml#/plat_{plat_id}'
  /internal/v1/plats:
    $ref: './paths/plat.yaml#/postPlat'
components:
  schemas:
    SampleUser:
      type: object
      required:
        - username
      properties:
        username:
          type: string
          example: 'sample_user'
