openapi: 3.0.3
info:
  title: stlatica_internal_api
  version: 0.1.0
  description: stlatica internal api
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
    description: go production server
  - url: http://localhost:4010
    description: prism mock server
paths:
  /internal/v1/users/{user_id}:
    $ref: './paths/users.yaml#/users_{user_id}'
  /internal/v1/users/{user_id}/icon:
    $ref: './paths/users.yaml#/users_{user_id}_icon'
  /internal/v1/users:
    $ref: './paths/users.yaml#/users'
  /internal/v1/users/{user_id}/follows:
    $ref: './paths/follows.yaml#/users_{user_id}_follows'
  /internal/v1/users/{user_id}/followers:
    $ref: './paths/follows.yaml#/users_{user_id}_followers'
  /internal/v1/users/{user_id}/follow:
    $ref: './paths/follows.yaml#/users_{user_id}_follow'
  /internal/v1/plats/{plat_id}:
    $ref: './paths/plats.yaml#/plat_{plat_id}'
  /internal/v1/plats/{plat_id}/favorites:
    $ref: './paths/plats.yaml#/favorite_{plat_id}'
  /internal/v1/plats:
    $ref: './paths/plats.yaml#/plats'
  /internal/v1/timelines/{timeline_id}:
    $ref: './paths/timelines.yaml#/timelines_{timeline_id}'
  /internal/v1/timelines:
    $ref: './paths/timelines.yaml#/timelines'
  /internal/v1/images/{image_id}:
    $ref: './paths/images.yaml#/images_{image_id}'
  /internal/v1/images:
    $ref: './paths/images.yaml#/images'
  /internal/v1/login:
    $ref: './paths/login.yaml#/login'
security:
  - Bearer: []
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
