version: "3.9"
x-common: &common-settings
  build:
    context: ./
    dockerfile: docker/Dockerfile
  volumes:
    - type: bind
      source: ./
      target: /openapi
  working_dir: /openapi
  init: true

services:
  redocly-cli:
    <<: *common-settings
  internal-preview:
    <<: *common-settings
    container_name: stlatica-openapi-preview-internal
    restart: always
    ports:
      - "127.0.0.1:2940:2940"
      - "127.0.0.1:32201:32201"
    command: redocly preview-docs --host 0.0.0.0 internalapi/openapi.yaml -p 2940
  external-preview:
    <<: *common-settings
    container_name: stlatica-openapi-preview-external
    restart: always
    ports:
      - "127.0.0.1:2941:2941"
      # redoclyのオプション見た感じホットリロードのポートが変更できないっぽいので、external previewのホットリロードを利用する際はコメントアウトで制御してください
      # - "127.0.0.1:32201:32201"
    command: redocly preview-docs --host 0.0.0.0 externalapi/openapi.yaml -p 2941
