version: "3.9"
services:
  api_mock:
    image: stlatica_front_node
    volumes:
      - type: bind
        source: ./
        target: /app/express
      - type: bind
        source: ../shared/openapi
        target: /app/openapi
    ports:
      # nextjs
      - "127.0.0.1:3000:3000"
      # vitest
      - "127.0.0.1:51204:51204"
      # ladle
      - "127.0.0.1:61000:61000"
      - "127.0.0.1:24678:24678"
    working_dir: /app/express
    tty: true
