version: "3.9"
services:
  api_mock:
    image: stlatica_front_node
    volumes:
      - type: bind
        source: ./
        target: /app/express
      - type: bind
        source: ../shared/openapi
        target: /app/openapi
    ports:
      # nextjs
      - "127.0.0.1:4010:3000"
      # vitest
      - "127.0.0.1:8080:8080"
    working_dir: /app/express
    tty: true
