// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

import (
	"github.com/stlatica/stlatica/packages/backend/app/domains/types"
)

// Actor is Actor entity object.
type Actor struct { // ulid
	ActorID types.ActorID `json:"actor_id"`
	// name
	Name string `json:"name"`
	// Unix time
	CreatedAt types.UnixTime `json:"created_at"`
}

// GetActorID is get actor_id value, if receiver is nil, returns the specified value.
func (m *Actor) GetActorID() types.ActorID {
	if m == nil {
		return types.ActorID{}
	}
	return m.ActorID
}

// GetName is get name value, if receiver is nil, returns the specified value.
func (m *Actor) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

// GetCreatedAt is get created_at value, if receiver is nil, returns the specified value.
func (m *Actor) GetCreatedAt() types.UnixTime {
	if m == nil {
		return types.UnixTime(0)
	}
	return m.CreatedAt
}
