// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

import (
	"github.com/stlatica/stlatica/packages/backend/app/domains/types"
)

// Plat is Plat entity object.
type Plat struct { // ulid
	PlatID types.PlatID `json:"plat_id"`
	// actor_id
	ActorID types.ActorID `json:"actor_id"`
	// body text
	Content string `json:"content"`
	// Unix time
	CreatedAt types.UnixTime `json:"created_at"`
}

// GetPlatID is get plat_id value, if receiver is nil, returns the specified value.
func (m *Plat) GetPlatID() types.PlatID {
	if m == nil {
		return types.PlatID{}
	}
	return m.PlatID
}

// GetActorID is get actor_id value, if receiver is nil, returns the specified value.
func (m *Plat) GetActorID() types.ActorID {
	if m == nil {
		return types.ActorID{}
	}
	return m.ActorID
}

// GetContent is get content value, if receiver is nil, returns the specified value.
func (m *Plat) GetContent() string {
	if m == nil {
		return ""
	}
	return m.Content
}

// GetCreatedAt is get created_at value, if receiver is nil, returns the specified value.
func (m *Plat) GetCreatedAt() types.UnixTime {
	if m == nil {
		return types.UnixTime(0)
	}
	return m.CreatedAt
}
