// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

import (
	"github.com/stlatica/stlatica/packages/backend/app/domains/types"
)

// Plat is Plat entity object.
type Plat struct { // ulid
	PlatID types.PlatID `json:"plat_id"`
	// user_id
	UserID types.UserID `json:"user_id"`
	// body text
	Content string `json:"content"`
	// Unix time
	CreatedAt types.UnixTime `json:"created_at"`
	// Unix time
	UpdatedAt types.UnixTime `json:"updated_at"`
}

// GetPlatID is get plat_id value, if receiver is nil, returns the specified value.
func (m *Plat) GetPlatID() types.PlatID {
	if m == nil {
		return types.PlatID{}
	}
	return m.PlatID
}

// GetUserID is get user_id value, if receiver is nil, returns the specified value.
func (m *Plat) GetUserID() types.UserID {
	if m == nil {
		return types.UserID{}
	}
	return m.UserID
}

// GetContent is get content value, if receiver is nil, returns the specified value.
func (m *Plat) GetContent() string {
	if m == nil {
		return ""
	}
	return m.Content
}

// GetCreatedAt is get created_at value, if receiver is nil, returns the specified value.
func (m *Plat) GetCreatedAt() types.UnixTime {
	if m == nil {
		return types.UnixTime(0)
	}
	return m.CreatedAt
}

// GetUpdatedAt is get updated_at value, if receiver is nil, returns the specified value.
func (m *Plat) GetUpdatedAt() types.UnixTime {
	if m == nil {
		return types.UnixTime(0)
	}
	return m.UpdatedAt
}
