// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

import (
	"github.com/stlatica/stlatica/packages/backend/app/domains/types"
)

// TimelineBase is TimelineBase entity object.
type TimelineBase struct { // ulid
	TimelineID types.TimelineID `json:"timeline_id"`
	// user_id
	UserID types.UserID `json:"user_id"`
	// name
	Name string `json:"name"`
	// description
	Description string `json:"description"`
	// Unix time
	CreatedAt types.UnixTime `json:"created_at"`
	// Unix time
	UpdatedAt types.UnixTime `json:"updated_at"`

	R *TimelineBaseR `json:"-"`
}

// TimelineBaseR is where relationships are stored.
type TimelineBaseR struct {
	User *UserBase `json:"User"`
}

// TimelineBaseSlice is an alias for a slice of pointers to TimelineBase.
// This should almost always be used instead of []TimelineBase.
type TimelineBaseSlice []*TimelineBase

// GetTimelineID is get timeline_id value, if receiver is nil, returns the specified value.
func (m *TimelineBase) GetTimelineID() types.TimelineID {
	if m == nil {
		return types.TimelineID{}
	}
	return m.TimelineID
}

// GetUserID is get user_id value, if receiver is nil, returns the specified value.
func (m *TimelineBase) GetUserID() types.UserID {
	if m == nil {
		return types.UserID{}
	}
	return m.UserID
}

// GetName is get name value, if receiver is nil, returns the specified value.
func (m *TimelineBase) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

// GetDescription is get description value, if receiver is nil, returns the specified value.
func (m *TimelineBase) GetDescription() string {
	if m == nil {
		return ""
	}
	return m.Description
}

// GetCreatedAt is get created_at value, if receiver is nil, returns the specified value.
func (m *TimelineBase) GetCreatedAt() types.UnixTime {
	if m == nil {
		return types.UnixTime(0)
	}
	return m.CreatedAt
}

// GetUpdatedAt is get updated_at value, if receiver is nil, returns the specified value.
func (m *TimelineBase) GetUpdatedAt() types.UnixTime {
	if m == nil {
		return types.UnixTime(0)
	}
	return m.UpdatedAt
}
