// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

import (
	"github.com/stlatica/stlatica/packages/backend/app/domains/types"
)

// Timeline is Timeline entity object.
type Timeline struct { // ulid
	TimelineID types.TimelineID `json:"timeline_id"`
	// user_id
	UserID types.UserID `json:"user_id"`
	// name
	Name string `json:"name"`
	// description
	Description string `json:"description"`
	// Unix time
	CreatedAt types.UnixTime `json:"created_at"`
	// Unix time
	UpdatedAt types.UnixTime `json:"updated_at"`
}

// GetTimelineID is get timeline_id value, if receiver is nil, returns the specified value.
func (m *Timeline) GetTimelineID() types.TimelineID {
	if m == nil {
		return types.TimelineID{}
	}
	return m.TimelineID
}

// GetUserID is get user_id value, if receiver is nil, returns the specified value.
func (m *Timeline) GetUserID() types.UserID {
	if m == nil {
		return types.UserID{}
	}
	return m.UserID
}

// GetName is get name value, if receiver is nil, returns the specified value.
func (m *Timeline) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

// GetDescription is get description value, if receiver is nil, returns the specified value.
func (m *Timeline) GetDescription() string {
	if m == nil {
		return ""
	}
	return m.Description
}

// GetCreatedAt is get created_at value, if receiver is nil, returns the specified value.
func (m *Timeline) GetCreatedAt() types.UnixTime {
	if m == nil {
		return types.UnixTime(0)
	}
	return m.CreatedAt
}

// GetUpdatedAt is get updated_at value, if receiver is nil, returns the specified value.
func (m *Timeline) GetUpdatedAt() types.UnixTime {
	if m == nil {
		return types.UnixTime(0)
	}
	return m.UpdatedAt
}
