version: "3.9"
services:
  api_mock:
    build:
      context: docker
      dockerfile: Dockerfile.node
      target: dev
    volumes:
      - type: bind
        source: ./
        target: /app/express
      - type: bind
        source: ../shared/openapi
        target: /app/openapi
    ports:
      - "127.0.0.1:8080:8080"
    working_dir: /app/express
    tty: true
    init: true