version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      # sharedアクセス等する場合は上げる
      context: ./
      dockerfile: Dockerfile
    # コンテナ終了を防ぎ中に入れるように
    tty: true
    ports:
      - "3000:3000"
      - "3010:3010"
    volumes:
      - type: bind
        source: ./
        target: /app
      - "/app/.pnpm-store"
      - "/app/node_modules"
    working_dir: /app
  prism-internal:
    container_name: prism-internal
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 /tmp/api.oas3.yml"
    volumes:
      - ../shared/openapi/internalapi/openapi.yaml:/tmp/api.oas3.yml:ro
    ports:
      - "4010:4010"
  prism-external:
    container_name: prism-external
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 /tmp/api.oas3.yml"
    volumes:
      - ../shared/openapi/externalapi/openapi.yaml:/tmp/api.oas3.yml:ro
    ports:
      - "4011:4010"
