version: "3.9"
services:
  front_dev:
    image: stlatica_front_node
    container_name: stlatica_front_dev
    volumes:
      - type: bind
        source: ./
        target: /app/packages/frontend
      - type: bind
        source: ../shared/
        target: /app/packages/shared
    # ports:
    #   - "127.0.0.1:3000:3000"
    network_mode: host
    working_dir: /app/packages/frontend
    tty: true

  nextjs:
    build:
      # sharedアクセス等する場合は上げる
      context: ../../
      dockerfile: packages/frontend/Dockerfile
    # コンテナ終了を防ぎ中に入れるように
    tty: true
    ports:
      - "3000:3000"
      - "3010:3010"
    volumes:
      - type: bind
        source: ./
        target: /app/packages/frontend
    working_dir: /app/packages/frontend
  # prism-internal:
  #   container_name: prism-internal
  #   image: stoplight/prism:4
  #   command: "mock -h 0.0.0.0 /tmp/api.oas3.yml"
  #   volumes:
  #     - ../shared/openapi/internalapi/openapi.yaml:/tmp/api.oas3.yml:ro
  #   ports:
  #     - "4010:4010"
