version: "3.9"
services:
  front_dev:
    image: stlatica_front_node
    container_name: stlatica_front_dev
    volumes:
      - type: bind
        source: ./
        target: /app/packages/frontend
      - type: bind
        source: ../shared/
        target: /app/packages/shared
    ports:
      # nextjs
      # - "127.0.0.1:3000:3000"
      - "127.0.0.1:3000:3000"
      # vitest
      # - "127.0.0.1:51204:51204"
      - "127.0.0.1:51204:51204"
      - "127.0.0.1:61000:61000"
    working_dir: /app/packages/frontend
    tty: true

  playwright_vrt:
    image: playwright-vrt
    volumes:
      - type: bind
        source: "./"
        target: /app
    ports:
      - 127.0.0.1:9323:9323

  # prism-internal:
  #   container_name: prism-internal
  #   image: stoplight/prism:4
  #   command: "mock -h 0.0.0.0 /tmp/api.oas3.yml"
  #   volumes:
  #     - ../shared/openapi/internalapi/openapi.yaml:/tmp/api.oas3.yml:ro
  #   ports:
  #     - "4010:4010"
