/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * stlatica_internal_api
 * stlatica internal api
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorResponseCode } from './errorResponseCode';

export interface ErrorResponse {
  code: ErrorResponseCode;
  message: string;
}
