/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * stlatica_internal_api
 * stlatica internal api
 * OpenAPI spec version: 0.1.0
 */

export * from './errorResponse';
export * from './errorResponseCode';
export * from './plat';
export * from './platID';
export * from './platPost';
export * from './sampleUser';
export * from './user';
export * from './userIDDef2';
export * from './userId';