/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * stlatica_internal_api
 * stlatica internal api
 * OpenAPI spec version: 0.1.0
 */
import type { PlatID } from './platID';

/**
 * plat
 */
export interface Plat {
  /** platの本文 */
  content: string;
  plat_id: PlatID;
}
