/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * stlatica_internal_api
 * stlatica internal api
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from './userId';

/**
 * plat
 */
export interface PlatPost {
  /** platの本文 */
  content: string;
  user_id: UserId;
}
