/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * stlatica_internal_api
 * stlatica internal api
 * OpenAPI spec version: 0.1.0
 */

/**
 * userを識別するための一意のID \
actor_idのfrontend向けエイリアスであり、actor_idと同一の値を持つ

 */
export type UserIDDef2 = string;
