// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package openapi

import (
	"time"
)

// Defines values for ErrorResponseCode.
const (
	BADREQUEST          ErrorResponseCode = "BAD_REQUEST"
	INTERNALSERVERERROR ErrorResponseCode = "INTERNAL_SERVER_ERROR"
	MISSINGPARAMETER    ErrorResponseCode = "MISSING_PARAMETER"
	NOTFOUND            ErrorResponseCode = "NOT_FOUND"
	SERVICEUNAVAILABLE  ErrorResponseCode = "SERVICE_UNAVAILABLE"
	UNAUTHORIZED        ErrorResponseCode = "UNAUTHORIZED"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    ErrorResponseCode `json:"code"`
	Message string            `json:"message"`
}

// ErrorResponseCode defines model for ErrorResponse.Code.
type ErrorResponseCode string

// Plat plat
type Plat struct {
	// Content platの本文
	Content string `json:"content"`

	// CreatedAt platが作成された日時(ISO8601)
	CreatedAt time.Time `json:"created_at"`

	// Images platに添付された画像のURL
	Images *[]string `json:"images,omitempty"`

	// PlatId platを識別するための一意のID
	PlatId PlatID `json:"plat_id"`
}

// PlatID platを識別するための一意のID
type PlatID = string

// PlatPost plat
type PlatPost struct {
	// Content platの本文
	Content string `json:"content"`

	// UserId userを識別するための一意のID
	UserId UserID `json:"user_id"`
}

// User user
type User struct {
	// FollowersCount follower数
	FollowersCount int `json:"followers_count"`

	// FollowingCount following数
	FollowingCount int `json:"following_count"`

	// Icon ユーザのアイコン画像のURL
	Icon string `json:"icon"`

	// IsPublic 公開アカウントであるかどうか \
	// external apiのmanuallyApprovesFollowersと同一の値となる
	IsPublic bool `json:"is_public"`

	// Summary ユーザのプロフィール
	Summary string `json:"summary"`

	// UserId userを識別するための一意のID
	UserId UserID `json:"user_id"`

	// Username 画面上に表示されるユーザ名
	Username string `json:"username"`
}

// UserID userを識別するための一意のID
type UserID = string

// PlatId defines model for plat_id.
type PlatId = string

// TimelineId defines model for timeline_id.
type TimelineId = string

// UserId defines model for user_id.
type UserId = string

// PostPlatJSONRequestBody defines body for PostPlat for application/json ContentType.
type PostPlatJSONRequestBody = PlatPost
