// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package openapi

// Defines values for ErrorResponseCode.
const (
	BADREQUEST          ErrorResponseCode = "BAD_REQUEST"
	INTERNALSERVERERROR ErrorResponseCode = "INTERNAL_SERVER_ERROR"
	MISSINGPARAMETER    ErrorResponseCode = "MISSING_PARAMETER"
	NOTFOUND            ErrorResponseCode = "NOT_FOUND"
	SERVICEUNAVAILABLE  ErrorResponseCode = "SERVICE_UNAVAILABLE"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    ErrorResponseCode `json:"code"`
	Message string            `json:"message"`
}

// ErrorResponseCode defines model for ErrorResponse.Code.
type ErrorResponseCode string

// User user
type User struct {
	// FollowersCount follower数
	FollowersCount int `json:"followers_count"`

	// FollowingCount following数
	FollowingCount int `json:"following_count"`

	// Icon ユーザのアイコン画像のURL
	Icon string `json:"icon"`

	// IsPublic 公開アカウントであるかどうか \
	// external apiのmanuallyApprovesFollowersと同一の値となる
	IsPublic bool `json:"is_public"`

	// Summary ユーザのプロフィール
	Summary string `json:"summary"`

	// UserId userを識別するための一意のID \
	// actor_idのfrontend向けエイリアスであり、actor_idと同一の値を持つ
	UserId UserID `json:"user_id"`

	// Username 画面上に表示されるユーザ名
	Username string `json:"username"`
}

// UserID userを識別するための一意のID \
// actor_idのfrontend向けエイリアスであり、actor_idと同一の値を持つ
type UserID = string

// UserId defines model for user_id.
type UserId = string
