name: build
run-name: build was executed by ${{ github.actor }}

on: [push]

jobs:
  changes:
    runs-on: ubuntu-20.04
    outputs:
      is_frontend: ${{ steps.filter.outputs.is_frontend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            is_frontend: 
              - 'packages/frontend/**'

  visual-regression-testing:
    needs: changes
    if: ${{ needs.changes.outputs.is_frontend == 'true' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: packages/frontend
    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # node.jsをインストール
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: packages/frontend/

      # pnpm 8をインストール
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # https://playwrightsolutions.com/playwright-github-action-to-cache-the-browser-binaries/
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      # 依存関係先をインストール
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # スナップショットテスト(vrt)
      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps
      - name: check snapshot
        run: pnpm ci:vrt
